
stack = []
stack.append("R")
stack.append("W")
stack.append("A")
stack.append("N")
stack.append("D")
stack.append("A")
stack.append("L")
stack.append("I")
stack.append("F")
stack.append("E")
reversed_word = ""
reversed_word += stack.pop()
reversed_word += stack.pop()
reversed_word += stack.pop()
reversed_word += stack.pop()
reversed_word += stack.pop()
reversed_word += stack.pop()
reversed_word += stack.pop()
reversed_word += stack.pop()
reversed_word += stack.pop()
reversed_word += stack.pop()
print("Reversed word:", reversed_word)
